export const fileMapping: Map<string, string> = new Map([
    ['savesets.file', 'internal_file_id'],
    ['internal_study_id', 'study.internal_study_id'],
    ['savesets.donor', 'donors.internal_donor_id'],
    ['gender', 'donors.gender'],
    ['ethnicity', 'donors.ethnicity'],
    ['age_at_recruitment', 'donors.age_at_recruitment'],
    ['vital_status', 'donors.vital_status'],
    ['donor_id', 'donors.donor_id'],
    ['files.internal_file_id', 'internal_file_id'],
    ['internal_donor_id', 'donors.internal_donor_id'],
    ['name', 'study.name'],
    ['diagnoses.tagged_mondo.name', 'donors.diagnoses.tagged_mondo.name'],
]);

export const donorMapping: Map<string, string> = new Map([
    ['donors.diagnoses.tagged_mondo.name', 'diagnoses.tagged_mondo.name'],
    ['donors.diagnoses.tagged_mondo.main_category', 'diagnoses.tagged_mondo.main_category'],
    ['donors.observed_phenotype_tagged.main_category', 'observed_phenotype_tagged.main_category'],
    ['donors.observed_phenotype_tagged.name', 'observed_phenotype_tagged.name'],
    ['donors.diagnoses.tagged_icd.main_category', 'diagnoses.tagged_icd.main_category'],
    ['donors.diagnoses.tagged_icd.name', 'diagnoses.tagged_icd.name'],
    ['population', 'study.population'],
    ['domain', 'study.domain'],
    ['internal_study_id', 'study.internal_study_id'],
    ['savesets.donor', 'internal_donor_id'],
    ['savesets.file', 'files.internal_file_id'],
    ['data_category', 'files.data_category'],
    ['data_type', 'files.data_type'],
    ['file_format', 'files.file_format'],
    ['data_access', 'files.data_access'],
    ['platform', 'files.platform'],
    ['experimental_strategy', 'files.experimental_strategy'],
    ['is_harmonized', 'files.is_harmonized'],
    ['internal_file_id', 'files.internal_file_id'],
    ['donors.internal_donor_id', 'internal_donor_id'],
    ['name', 'study.name'],
]);

export const studyMapping: Map<string, string> = new Map([
    ['savesets.donor', 'donors.internal_donor_id'],
    ['savesets.file', 'files.internal_file_id'],
    ['data_category', 'files.data_category'],
    ['data_type', 'files.data_type'],
    ['file_format', 'files.file_format'],
    ['data_access', 'files.data_access'],
    ['platform', 'files.platform'],
    ['experimental_strategy', 'files.experimental_strategy'],
    ['is_harmonized', 'files.is_harmonized'],
    ['internal_file_id', 'files.internal_file_id'],
    ['study.name', 'name'],
    ['study.domain', 'domain'],
    ['gender', 'donors.gender'],
    ['ethnicity', 'donors.ethnicity'],
    ['vital_status', 'donors.vital_status'],
    ['age_at_recruitment', 'donors.age_at_recruitment'],
    ['internal_donor_id', 'donors.internal_donor_id'],
    ['observed_phenotype_tagged.main_category', 'donors.observed_phenotype_tagged.main_category'],
    ['observed_phenotype_tagged.name', 'donors.observed_phenotype_tagged.name'],
    ['diagnoses.tagged_mondo.name', 'donors.diagnoses.tagged_mondo.name'],
    ['diagnoses.tagged_mondo.main_category', 'donors.diagnoses.tagged_mondo.main_category'],
    ['diagnoses.tagged_icd.main_category', 'donors.diagnoses.tagged_icd.main_category'],
    ['diagnoses.tagged_icd.name', 'donors.diagnoses.tagged_icd.name'],
]);
